export const walletText = {
  en: {
    walletTitle: 'Wasel Wallet',
    balance: 'Available Balance',
    pending: 'Pending',
    rewards: 'Rewards',
    hideBalance: 'Hide balance',
    showBalance: 'Show balance',
    addMoney: 'Add Money',
    withdraw: 'Withdraw',
    sendMoney: 'Send',
    overview: 'Overview',
    transactions: 'Transactions',
    send: 'Send',
    rewardsTab: 'Rewards',
    insights: 'Insights',
    settings: 'Settings',
    recentTransactions: 'Recent Transactions',
    viewAll: 'View All',
    noTransactions: 'Transactions will appear here as soon as your wallet becomes active',
    quickActions: 'Core Actions',
    topUpAmount: 'Top-up Amount (JOD)',
    paymentMethod: 'Payment Method',
    card: 'Credit/Debit Card',
    applePay: 'Apple Pay',
    bankTransfer: 'Bank Transfer',
    cliq: 'CliQ',
    topUp: 'Top Up',
    withdrawAmount: 'Withdrawal Amount (JOD)',
    bankAccount: 'Bank Account / IBAN',
    instant: 'Instant',
    standard: 'Standard (1-3 days)',
    confirmWithdraw: 'Withdraw',
    recipientId: 'Recipient User ID',
    sendAmount: 'Amount (JOD)',
    noteOptional: 'Note (optional)',
    confirmSend: 'Send Money',
    activeRewards: 'Active Rewards',
    claimedRewards: 'Claimed Rewards',
    claim: 'Claim',
    expires: 'Expires',
    noRewards: 'No rewards available',
    spendingInsights: 'Spending Insights',
    thisMonth: 'This Month',
    vsLastMonth: 'vs last month',
    earned: 'Earned',
    spent: 'Spent',
    monthlyTrend: 'Monthly Trend',
    categoryBreakdown: 'Category Breakdown',
    securityPin: 'Wallet PIN',
    setPin: 'Set PIN',
    changePin: 'Change PIN',
    pinDescription: 'Protect transactions with a 4-digit PIN',
    autoTopUp: 'Auto Top-Up',
    autoTopUpDesc: 'Automatically add funds when balance drops below threshold',
    threshold: 'Threshold (JOD)',
    topUpAmountSetting: 'Top-up Amount (JOD)',
    subscription: 'Wasel Plus',
    subscribeNow: 'Subscribe Now',
    activeSubscription: 'Active Subscription',
    escrow: 'Active Escrows',
    held: 'Held',
    processing: 'Processing...',
    pinDigits: 'Enter 4-digit PIN',
    carbonSaved: 'CO2 Saved',
    totalTx: 'Total Transactions',
    jod: 'JOD',
    liveStatus: 'Live',
    walletSubtitle: 'Payments, balance, and rewards',
    redirectingToSignIn: 'Redirecting to sign in...',
    walletUnavailableTitle: 'Wallet experience is being finalized',
    walletUnavailableDescription: 'We are wiring payments, trust checks, and settlement flows. Complete backend setup to unlock the full wallet journey.',
    walletUnavailableHint: 'A more polished money experience is on the way',
    rewardsEmptyHint: 'Complete trips to earn rewards',
    availableLabel: 'Available',
    freeLabel: 'Free',
    userIdPlaceholder: 'User ID',
    notePlaceholder: 'Note...',
    maskedBalance: '******',
    maskedShort: '**',
    maskedPin: '****',
    activeLabel: 'Active',
    invalidAmount: 'Enter a valid amount',
    enterBankAccount: 'Enter bank account',
    insufficientBalance: 'Insufficient balance',
    enterRecipientId: 'Enter recipient ID',
    pinMustBeFourDigits: 'PIN must be 4 digits',
    walletLoadError: 'Unable to load wallet right now',
    refreshed: 'Refreshed',
    autoTopUpEnabledToast: 'Auto top-up enabled',
    autoTopUpDisabledToast: 'Auto top-up disabled',
    welcomeToPlus: 'Welcome to Wasel Plus!',
    rewardClaimed: 'Reward claimed!',
    pinSetSuccess: 'PIN set successfully',
  },
  ar: {
    walletTitle: 'محفظة واصل',
    balance: 'الرصيد المتاح',
    pending: 'معلق',
    rewards: 'المكافآت',
    hideBalance: 'إخفاء الرصيد',
    showBalance: 'إظهار الرصيد',
    addMoney: 'إضافة رصيد',
    withdraw: 'سحب',
    sendMoney: 'إرسال',
    overview: 'نظرة عامة',
    transactions: 'المعاملات',
    send: 'إرسال',
    rewardsTab: 'المكافآت',
    insights: 'التحليلات',
    settings: 'الإعدادات',
    recentTransactions: 'آخر المعاملات',
    viewAll: 'عرض الكل',
    noTransactions: 'ستظهر المعاملات هنا فور تفعيل المحفظة',
    quickActions: 'الإجراءات الأساسية',
    topUpAmount: 'مبلغ الشحن (دينار)',
    paymentMethod: 'طريقة الدفع',
    card: 'بطاقة ائتمان أو خصم',
    applePay: 'أبل باي',
    bankTransfer: 'تحويل بنكي',
    cliq: 'كليك',
    topUp: 'شحن',
    withdrawAmount: 'مبلغ السحب (دينار)',
    bankAccount: 'الحساب البنكي / IBAN',
    instant: 'فوري',
    standard: 'عادي (1-3 أيام)',
    confirmWithdraw: 'سحب',
    recipientId: 'معرف المستلم',
    sendAmount: 'المبلغ (دينار)',
    noteOptional: 'ملاحظة (اختياري)',
    confirmSend: 'إرسال المال',
    activeRewards: 'المكافآت النشطة',
    claimedRewards: 'المكافآت المستلمة',
    claim: 'استلام',
    expires: 'ينتهي',
    noRewards: 'لا توجد مكافآت متاحة',
    spendingInsights: 'تحليلات الإنفاق',
    thisMonth: 'هذا الشهر',
    vsLastMonth: 'مقارنة بالشهر الماضي',
    earned: 'المكتسب',
    spent: 'المنفق',
    monthlyTrend: 'الاتجاه الشهري',
    categoryBreakdown: 'التفصيل حسب الفئة',
    securityPin: 'رمز PIN للمحفظة',
    setPin: 'تعيين PIN',
    changePin: 'تغيير PIN',
    pinDescription: 'احم معاملاتك برمز من 4 أرقام',
    autoTopUp: 'شحن تلقائي',
    autoTopUpDesc: 'أضف رصيداً تلقائياً عندما ينخفض الرصيد عن الحد المحدد',
    threshold: 'الحد الأدنى (دينار)',
    topUpAmountSetting: 'مبلغ الشحن (دينار)',
    subscription: 'واصل بلس',
    subscribeNow: 'اشترك الآن',
    activeSubscription: 'اشتراك فعال',
    escrow: 'عمليات الضمان النشطة',
    held: 'محجوز',
    processing: 'جارٍ المعالجة...',
    pinDigits: 'أدخل رمزاً من 4 أرقام',
    carbonSaved: 'انبعاثات CO2 التي تم توفيرها',
    totalTx: 'إجمالي المعاملات',
    jod: 'دينار',
    liveStatus: 'نشط',
    walletSubtitle: 'المدفوعات والرصيد والمكافآت',
    redirectingToSignIn: 'جارٍ تحويلك إلى تسجيل الدخول...',
    walletUnavailableTitle: 'المحفظة قيد الإطلاق',
    walletUnavailableDescription: 'نجهز تدفق المدفوعات والأمان والتسوية. أكمل إعداد الخلفية لرؤية تجربة المحفظة الكاملة.',
    walletUnavailableHint: 'تجربة مالية أكثر تنسيقاً قريباً',
    rewardsEmptyHint: 'أكمل رحلات لربح مكافآت',
    availableLabel: 'الرصيد المتاح',
    freeLabel: 'مجاني',
    userIdPlaceholder: 'معرف المستلم',
    notePlaceholder: 'ملاحظة...',
    maskedBalance: '******',
    maskedShort: '**',
    maskedPin: '****',
    activeLabel: 'نشط',
    invalidAmount: 'أدخل مبلغاً صحيحاً',
    enterBankAccount: 'أدخل رقم الحساب',
    insufficientBalance: 'الرصيد غير كافٍ',
    enterRecipientId: 'أدخل معرف المستلم',
    pinMustBeFourDigits: 'الرمز يجب أن يكون 4 أرقام',
    walletLoadError: 'تعذر تحميل المحفظة الآن',
    refreshed: 'تم التحديث',
    autoTopUpEnabledToast: 'تم تفعيل الشحن التلقائي',
    autoTopUpDisabledToast: 'تم إيقاف الشحن التلقائي',
    welcomeToPlus: 'مبروك! تم الاشتراك في واصل بلس',
    rewardClaimed: 'تم استلام المكافأة!',
    pinSetSuccess: 'تم تعيين PIN بنجاح',
  },
} as const;
